{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altnoir.poopsky",
    "module": "PoopSkyMod",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.6.jar",
          "url": "PoopSkyMod-1.1.6.jar",
          "size": 7417785,
          "sha512": "708842543c38d23a36af4b31020a95f0413857b27abac62eab22710af90a260a3df603772506e4354de10ef886a105f2bcf250cc5eaec753ad9ea82fcb08bbdd",
          "sha256": "9981e18a265e82db29ca04e6acfa1ae9b8e7455feb3493f97ee4e54f25d050f4",
          "sha1": "84a975ae9e500765dd2f72db8c0a2f4483d9acac",
          "md5": "f650bb5af45566a1a0a7d384d9c65ca6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.6.jar",
          "url": "PoopSkyMod-1.1.6.jar",
          "size": 7417785,
          "sha512": "708842543c38d23a36af4b31020a95f0413857b27abac62eab22710af90a260a3df603772506e4354de10ef886a105f2bcf250cc5eaec753ad9ea82fcb08bbdd",
          "sha256": "9981e18a265e82db29ca04e6acfa1ae9b8e7455feb3493f97ee4e54f25d050f4",
          "sha1": "84a975ae9e500765dd2f72db8c0a2f4483d9acac",
          "md5": "f650bb5af45566a1a0a7d384d9c65ca6"
        }
      ]
    }
  ]
}
