{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altnoir.poopsky",
    "module": "PoopSkyMod",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.6.jar",
          "url": "PoopSkyMod-1.1.6.jar",
          "size": 7417785,
          "sha512": "e45a16b85e66ed738124069d515bef4cbb831dcb00afde96f0101aeb94954ae3d5a5bc733c6e3ed1bf3df0fd58ad4d9b19976af73cdab42a019ee63197961412",
          "sha256": "c6204f59ec11c62ed00025883e9a3e883c5a3f616c7925062b13dbcc74817b0d",
          "sha1": "7a5d56dc26d0b897d35c94ad37632c2044336004",
          "md5": "ba1e42a917377f8bb5b9917bd453f0b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.6.jar",
          "url": "PoopSkyMod-1.1.6.jar",
          "size": 7417785,
          "sha512": "e45a16b85e66ed738124069d515bef4cbb831dcb00afde96f0101aeb94954ae3d5a5bc733c6e3ed1bf3df0fd58ad4d9b19976af73cdab42a019ee63197961412",
          "sha256": "c6204f59ec11c62ed00025883e9a3e883c5a3f616c7925062b13dbcc74817b0d",
          "sha1": "7a5d56dc26d0b897d35c94ad37632c2044336004",
          "md5": "ba1e42a917377f8bb5b9917bd453f0b7"
        }
      ]
    }
  ]
}
