{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altnoir.poopsky",
    "module": "PoopSkyMod",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.6.jar",
          "url": "PoopSkyMod-1.1.6.jar",
          "size": 7417785,
          "sha512": "5464c4c15885e678f6f7317b3c07db8368bf626f40a55b85e330f96f35a293a13d4c136d55c20f7d722c7f7c8a2f48db6f8dc83fd16505a96b4484e18c1b12d4",
          "sha256": "b1b63c6d98f305462e3e1441e2316d6e369e13a7355e8798c97c17430a947a02",
          "sha1": "48627ee26f54922700e96a33ed48f5fb9620e4a5",
          "md5": "5494abb8850d19d2abbcc3d95cd0b3bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.6.jar",
          "url": "PoopSkyMod-1.1.6.jar",
          "size": 7417785,
          "sha512": "5464c4c15885e678f6f7317b3c07db8368bf626f40a55b85e330f96f35a293a13d4c136d55c20f7d722c7f7c8a2f48db6f8dc83fd16505a96b4484e18c1b12d4",
          "sha256": "b1b63c6d98f305462e3e1441e2316d6e369e13a7355e8798c97c17430a947a02",
          "sha1": "48627ee26f54922700e96a33ed48f5fb9620e4a5",
          "md5": "5494abb8850d19d2abbcc3d95cd0b3bf"
        }
      ]
    }
  ]
}
