{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altnoir.poopsky",
    "module": "PoopSkyMod",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.7.jar",
          "url": "PoopSkyMod-1.1.7.jar",
          "size": 7417785,
          "sha512": "084a2efdb813dd87b97a482e32c5241572ea6c4702f3c56474171f99464d665639a96e75c35a919de4fdb3adfdaad3b85dbec3acf520d405fd881a47bce283f6",
          "sha256": "27ea2bd69576fb152e91fa2d45fc44eb71da6f47b40e5e3f0d8dc260a7773a90",
          "sha1": "fb2876544198d434a47ee3d2a45f05d87620a362",
          "md5": "864b002fba524b4ebb8ae499660df89a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PoopSkyMod-1.1.7.jar",
          "url": "PoopSkyMod-1.1.7.jar",
          "size": 7417785,
          "sha512": "084a2efdb813dd87b97a482e32c5241572ea6c4702f3c56474171f99464d665639a96e75c35a919de4fdb3adfdaad3b85dbec3acf520d405fd881a47bce283f6",
          "sha256": "27ea2bd69576fb152e91fa2d45fc44eb71da6f47b40e5e3f0d8dc260a7773a90",
          "sha1": "fb2876544198d434a47ee3d2a45f05d87620a362",
          "md5": "864b002fba524b4ebb8ae499660df89a"
        }
      ]
    }
  ]
}
