name: Publish

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      modversion: ${{ steps.get_version.outputs.modversion }}
      mcversion: ${{ steps.get_version.outputs.mcversion }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get version
        id: get_version
        run: |
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "modversion=$MOD_VERSION" >> $GITHUB_OUTPUT
          MC_VERSION=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)
          echo "mcversion=$MC_VERSION" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.modversion }}
          name: PoopSky-${{ steps.get_version.outputs.mcversion }}-${{ steps.get_version.outputs.modversion }}
          generate_release_notes: true
          files: |
            build/libs/*.jar

  maven:
    needs: release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Publish
        run: ./gradlew publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          destination_dir: ./repo

  bump:
    needs: [release, maven]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump
        id: bump
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ needs.release.outputs.modversion }}"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
          sed -i "s/^mod_version=.*/mod_version=$NEW_VERSION/" gradle.properties

      - name: Commit
        run: |
          git add gradle.properties
          git commit -m "Bump version to ${{ steps.bump_version.outputs.new }}"
          git push
